services:
  sim:
    build: 
      context: ./sim_ws
      dockerfile: Dockerfile
    image: syncai-simulation-base-image:latest
    container_name: syncai-simulation

    runtime: nvidia
    environment:
      # X11 forwarding
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/ubuntu/.Xauthority

      # NVIDIA settings      
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      # ROS 2 and Gazebo settings
      - ROS_DOMAIN_ID=0
      - CYCLONEDDS_URI=file:///home/ubuntu/sim_ws/config/cyclonedds.xml
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - GZ_SIM_RESOURCE_PATH=/home/ubuntu/sim_ws/install/syncai_demo_gz/share/syncai_demo_gz


    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/ubuntu/.Xauthority:ro
      - ./sim_ws:/home/ubuntu/sim_ws
      - ./data:/home/ubuntu/data
    
    # devices:
    #   - /dev/dri:/dev/dri
    
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped

  robot01:
    build:
      context: ./robot_ws
      dockerfile: Dockerfile
    image: syncai-robot-base-image:latest
    container_name: syncai-robot01

    runtime: nvidia

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/ubuntu/.Xauthority

      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      # ROS 2 DDS
      - ROS_DOMAIN_ID=0
      - CYCLONEDDS_URI=file:///home/ubuntu/data/cyclonedds.xml
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - SYNCAI_DATA_DIR=/home/ubuntu/data

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/ubuntu/.Xauthority:ro
      - ./robot_ws:/home/ubuntu/robot_ws
      - ./data/robot01:/home/ubuntu/data
      - ./map:/home/ubuntu/map
      - ./params:/home/ubuntu/params
    
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:18
    ports:
      - 5432:5432
    volumes:
      - ./data/db_data:/var/lib/postgresql
    tmpfs:
      - /tmp
      - /run
    restart: unless-stopped

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=${TEMPORAL_DB}
      - DB_PORT=${TEMPORAL_DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=postgresql
      - TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS}
      - TEMPORAL_CLI_ADDRESS=${TEMPORAL_CLI_ADDRESS}
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    ports:
      - 7233:7233
    tmpfs:
      - /tmp
      - /run
    restart: unless-stopped

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS}
      - TEMPORAL_CORS_ORIGINS=${TEMPORAL_CORS_ORIGINS}
      - TEMPORAL_UI_AUTH_DISABLED=true
      - TEMPORAL_UI_CSRF_COOKIE_INSECURE=true
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    ports:
      - ${TEMPORAL_UI_PORT}:8080
    tmpfs:
      - /tmp
      - /run
    restart: unless-stopped