module syncai_common { module msg { module dds_ {

  struct BridgeCommand_ {
    string request_id;
    string action;
    string payload_json;
  };

  struct BridgeCommandResponse_ {
    string request_id;
    boolean success;
    string message;
    string data_json;
  };

}; }; };
