/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: bridge_service.h
  Source: /home/syncrobotic/Documents/SyncAI-Simulation/robot_ws/src/syncai_bridge/internal/dds/bridge_service.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_BRIDGE_SERVICE_H
#define DDSC_BRIDGE_SERVICE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct syncai_common_msg_dds__BridgeCommand_
{
  char * request_id;
  char * action;
  char * payload_json;
} syncai_common_msg_dds__BridgeCommand_;

extern const dds_topic_descriptor_t syncai_common_msg_dds__BridgeCommand__desc;

#define syncai_common_msg_dds__BridgeCommand___alloc() \
((syncai_common_msg_dds__BridgeCommand_*) dds_alloc (sizeof (syncai_common_msg_dds__BridgeCommand_)));

#define syncai_common_msg_dds__BridgeCommand__free(d,o) \
dds_sample_free ((d), &syncai_common_msg_dds__BridgeCommand__desc, (o))

typedef struct syncai_common_msg_dds__BridgeCommandResponse_
{
  char * request_id;
  bool success;
  char * message;
  char * data_json;
} syncai_common_msg_dds__BridgeCommandResponse_;

extern const dds_topic_descriptor_t syncai_common_msg_dds__BridgeCommandResponse__desc;

#define syncai_common_msg_dds__BridgeCommandResponse___alloc() \
((syncai_common_msg_dds__BridgeCommandResponse_*) dds_alloc (sizeof (syncai_common_msg_dds__BridgeCommandResponse_)));

#define syncai_common_msg_dds__BridgeCommandResponse__free(d,o) \
dds_sample_free ((d), &syncai_common_msg_dds__BridgeCommandResponse__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_BRIDGE_SERVICE_H */
