/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: robot_state_ros2.h
  Source: /tmp/robot_state_ros2.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_ROBOT_STATE_ROS2_H
#define DDSC_ROBOT_STATE_ROS2_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_dds__Time_
{
  int32_t sec;
  uint32_t nanosec;
} std_msgs_msg_dds__Time_;

extern const dds_topic_descriptor_t std_msgs_msg_dds__Time__desc;

#define std_msgs_msg_dds__Time___alloc() \
((std_msgs_msg_dds__Time_*) dds_alloc (sizeof (std_msgs_msg_dds__Time_)));

#define std_msgs_msg_dds__Time__free(d,o) \
dds_sample_free ((d), &std_msgs_msg_dds__Time__desc, (o))

typedef struct std_msgs_msg_dds__Header_
{
  struct std_msgs_msg_dds__Time_ stamp;
  char * frame_id;
} std_msgs_msg_dds__Header_;

extern const dds_topic_descriptor_t std_msgs_msg_dds__Header__desc;

#define std_msgs_msg_dds__Header___alloc() \
((std_msgs_msg_dds__Header_*) dds_alloc (sizeof (std_msgs_msg_dds__Header_)));

#define std_msgs_msg_dds__Header__free(d,o) \
dds_sample_free ((d), &std_msgs_msg_dds__Header__desc, (o))

typedef struct geometry_msgs_msg_dds__Point_
{
  double x;
  double y;
  double z;
} geometry_msgs_msg_dds__Point_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Point__desc;

#define geometry_msgs_msg_dds__Point___alloc() \
((geometry_msgs_msg_dds__Point_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Point_)));

#define geometry_msgs_msg_dds__Point__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Point__desc, (o))

typedef struct geometry_msgs_msg_dds__Quaternion_
{
  double x;
  double y;
  double z;
  double w;
} geometry_msgs_msg_dds__Quaternion_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Quaternion__desc;

#define geometry_msgs_msg_dds__Quaternion___alloc() \
((geometry_msgs_msg_dds__Quaternion_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Quaternion_)));

#define geometry_msgs_msg_dds__Quaternion__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Quaternion__desc, (o))

typedef struct geometry_msgs_msg_dds__Pose_
{
  struct geometry_msgs_msg_dds__Point_ position;
  struct geometry_msgs_msg_dds__Quaternion_ orientation;
} geometry_msgs_msg_dds__Pose_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Pose__desc;

#define geometry_msgs_msg_dds__Pose___alloc() \
((geometry_msgs_msg_dds__Pose_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Pose_)));

#define geometry_msgs_msg_dds__Pose__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Pose__desc, (o))

typedef struct geometry_msgs_msg_dds__Vector3_
{
  double x;
  double y;
  double z;
} geometry_msgs_msg_dds__Vector3_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Vector3__desc;

#define geometry_msgs_msg_dds__Vector3___alloc() \
((geometry_msgs_msg_dds__Vector3_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Vector3_)));

#define geometry_msgs_msg_dds__Vector3__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Vector3__desc, (o))

typedef struct geometry_msgs_msg_dds__Twist_
{
  struct geometry_msgs_msg_dds__Vector3_ linear;
  struct geometry_msgs_msg_dds__Vector3_ angular;
} geometry_msgs_msg_dds__Twist_;

extern const dds_topic_descriptor_t geometry_msgs_msg_dds__Twist__desc;

#define geometry_msgs_msg_dds__Twist___alloc() \
((geometry_msgs_msg_dds__Twist_*) dds_alloc (sizeof (geometry_msgs_msg_dds__Twist_)));

#define geometry_msgs_msg_dds__Twist__free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_dds__Twist__desc, (o))

typedef struct syncai_common_msg_dds__RobotState_
{
  struct std_msgs_msg_dds__Header_ header;
  char * robot_id;
  char * robot_name;
  char * model;
  char * map_;
  struct geometry_msgs_msg_dds__Pose_ pose;
  struct geometry_msgs_msg_dds__Twist_ velocity;
  float battery_percentage;
  float battery_voltage;
} syncai_common_msg_dds__RobotState_;

extern const dds_topic_descriptor_t syncai_common_msg_dds__RobotState__desc;

#define syncai_common_msg_dds__RobotState___alloc() \
((syncai_common_msg_dds__RobotState_*) dds_alloc (sizeof (syncai_common_msg_dds__RobotState_)));

#define syncai_common_msg_dds__RobotState__free(d,o) \
dds_sample_free ((d), &syncai_common_msg_dds__RobotState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROBOT_STATE_ROS2_H */
