/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: test_robot_state.h
  Source: /tmp/test_robot_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_TEST_ROBOT_STATE_H
#define DDSC_TEST_ROBOT_STATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Time_
{
  int32_t sec;
  uint32_t nanosec;
} Time_;

extern const dds_topic_descriptor_t Time__desc;

#define Time___alloc() \
((Time_*) dds_alloc (sizeof (Time_)));

#define Time__free(d,o) \
dds_sample_free ((d), &Time__desc, (o))

typedef struct Header_
{
  struct Time_ stamp;
  char * frame_id;
} Header_;

extern const dds_topic_descriptor_t Header__desc;

#define Header___alloc() \
((Header_*) dds_alloc (sizeof (Header_)));

#define Header__free(d,o) \
dds_sample_free ((d), &Header__desc, (o))

typedef struct Point_
{
  double x;
  double y;
  double z;
} Point_;

extern const dds_topic_descriptor_t Point__desc;

#define Point___alloc() \
((Point_*) dds_alloc (sizeof (Point_)));

#define Point__free(d,o) \
dds_sample_free ((d), &Point__desc, (o))

typedef struct Quaternion_
{
  double x;
  double y;
  double z;
  double w;
} Quaternion_;

extern const dds_topic_descriptor_t Quaternion__desc;

#define Quaternion___alloc() \
((Quaternion_*) dds_alloc (sizeof (Quaternion_)));

#define Quaternion__free(d,o) \
dds_sample_free ((d), &Quaternion__desc, (o))

typedef struct Pose_
{
  struct Point_ position;
  struct Quaternion_ orientation;
} Pose_;

extern const dds_topic_descriptor_t Pose__desc;

#define Pose___alloc() \
((Pose_*) dds_alloc (sizeof (Pose_)));

#define Pose__free(d,o) \
dds_sample_free ((d), &Pose__desc, (o))

typedef struct Vector3_
{
  double x;
  double y;
  double z;
} Vector3_;

extern const dds_topic_descriptor_t Vector3__desc;

#define Vector3___alloc() \
((Vector3_*) dds_alloc (sizeof (Vector3_)));

#define Vector3__free(d,o) \
dds_sample_free ((d), &Vector3__desc, (o))

typedef struct Twist_
{
  struct Vector3_ linear;
  struct Vector3_ angular;
} Twist_;

extern const dds_topic_descriptor_t Twist__desc;

#define Twist___alloc() \
((Twist_*) dds_alloc (sizeof (Twist_)));

#define Twist__free(d,o) \
dds_sample_free ((d), &Twist__desc, (o))

typedef struct RobotState_
{
  struct Header_ header;
  char * robot_id;
  char * robot_name;
  char * model;
  char * map_;
  struct Pose_ pose;
  struct Twist_ velocity;
  float battery_percentage;
  float battery_voltage;
} RobotState_;

extern const dds_topic_descriptor_t RobotState__desc;

#define RobotState___alloc() \
((RobotState_*) dds_alloc (sizeof (RobotState_)));

#define RobotState__free(d,o) \
dds_sample_free ((d), &RobotState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_TEST_ROBOT_STATE_H */
