// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: command.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceId   string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Command    string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSec float32                `protobuf:"fixed32,3,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	// Types that are valid to be assigned to Protocol:
	//
	//	*CommandRequest_Modbus
	//	*CommandRequest_Rest
	Protocol      isCommandRequest_Protocol `protobuf_oneof:"protocol"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetTimeoutSec() float32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *CommandRequest) GetProtocol() isCommandRequest_Protocol {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *CommandRequest) GetModbus() *ModbusParams {
	if x != nil {
		if x, ok := x.Protocol.(*CommandRequest_Modbus); ok {
			return x.Modbus
		}
	}
	return nil
}

func (x *CommandRequest) GetRest() *RestParams {
	if x != nil {
		if x, ok := x.Protocol.(*CommandRequest_Rest); ok {
			return x.Rest
		}
	}
	return nil
}

type isCommandRequest_Protocol interface {
	isCommandRequest_Protocol()
}

type CommandRequest_Modbus struct {
	Modbus *ModbusParams `protobuf:"bytes,10,opt,name=modbus,proto3,oneof"`
}

type CommandRequest_Rest struct {
	Rest *RestParams `protobuf:"bytes,11,opt,name=rest,proto3,oneof"`
}

func (*CommandRequest_Modbus) isCommandRequest_Protocol() {}

func (*CommandRequest_Rest) isCommandRequest_Protocol() {}

type ModbusParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	UnitId        uint32                 `protobuf:"varint,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Address       uint32                 `protobuf:"varint,3,opt,name=address,proto3" json:"address,omitempty"`
	Value         bool                   `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModbusParams) Reset() {
	*x = ModbusParams{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModbusParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModbusParams) ProtoMessage() {}

func (x *ModbusParams) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModbusParams.ProtoReflect.Descriptor instead.
func (*ModbusParams) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *ModbusParams) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ModbusParams) GetUnitId() uint32 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *ModbusParams) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *ModbusParams) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type RestParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestParams) Reset() {
	*x = RestParams{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestParams) ProtoMessage() {}

func (x *RestParams) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestParams.ProtoReflect.Descriptor instead.
func (*RestParams) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *RestParams) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RestParams) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RestParams) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RestParams) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\x06bridge\"\xce\x01\n" +
	"\x0eCommandRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1f\n" +
	"\vtimeout_sec\x18\x03 \x01(\x02R\n" +
	"timeoutSec\x12.\n" +
	"\x06modbus\x18\n" +
	" \x01(\v2\x14.bridge.ModbusParamsH\x00R\x06modbus\x12(\n" +
	"\x04rest\x18\v \x01(\v2\x12.bridge.RestParamsH\x00R\x04restB\n" +
	"\n" +
	"\bprotocol\"o\n" +
	"\fModbusParams\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\rR\x06unitId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\rR\aaddress\x12\x14\n" +
	"\x05value\x18\x04 \x01(\bR\x05value\"\xc1\x01\n" +
	"\n" +
	"RestParams\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x129\n" +
	"\aheaders\x18\x04 \x03(\v2\x1f.bridge.RestParams.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data2P\n" +
	"\x0eCommandService\x12>\n" +
	"\vSendCommand\x12\x16.bridge.CommandRequest\x1a\x17.bridge.CommandResponseB<Z:github.com/nicosyncai/syncai-bridge/internal/grpcserver/pbb\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_command_proto_goTypes = []any{
	(*CommandRequest)(nil),  // 0: bridge.CommandRequest
	(*ModbusParams)(nil),    // 1: bridge.ModbusParams
	(*RestParams)(nil),      // 2: bridge.RestParams
	(*CommandResponse)(nil), // 3: bridge.CommandResponse
	nil,                     // 4: bridge.RestParams.HeadersEntry
}
var file_command_proto_depIdxs = []int32{
	1, // 0: bridge.CommandRequest.modbus:type_name -> bridge.ModbusParams
	2, // 1: bridge.CommandRequest.rest:type_name -> bridge.RestParams
	4, // 2: bridge.RestParams.headers:type_name -> bridge.RestParams.HeadersEntry
	0, // 3: bridge.CommandService.SendCommand:input_type -> bridge.CommandRequest
	3, // 4: bridge.CommandService.SendCommand:output_type -> bridge.CommandResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	file_command_proto_msgTypes[0].OneofWrappers = []any{
		(*CommandRequest_Modbus)(nil),
		(*CommandRequest_Rest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
