// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/map.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapRequest) Reset() {
	*x = GetMapRequest{}
	mi := &file_proto_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapRequest) ProtoMessage() {}

func (x *GetMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapRequest.ProtoReflect.Descriptor instead.
func (*GetMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_map_proto_rawDescGZIP(), []int{0}
}

type MapPose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Yaw           float32                `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapPose) Reset() {
	*x = MapPose{}
	mi := &file_proto_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapPose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapPose) ProtoMessage() {}

func (x *MapPose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapPose.ProtoReflect.Descriptor instead.
func (*MapPose) Descriptor() ([]byte, []int) {
	return file_proto_map_proto_rawDescGZIP(), []int{1}
}

func (x *MapPose) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapPose) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapPose) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type MapMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Resolution    float32                `protobuf:"fixed32,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Origin        *MapPose               `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapMetadata) Reset() {
	*x = MapMetadata{}
	mi := &file_proto_map_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMetadata) ProtoMessage() {}

func (x *MapMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMetadata.ProtoReflect.Descriptor instead.
func (*MapMetadata) Descriptor() ([]byte, []int) {
	return file_proto_map_proto_rawDescGZIP(), []int{2}
}

func (x *MapMetadata) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapMetadata) GetResolution() float32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *MapMetadata) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapMetadata) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapMetadata) GetOrigin() *MapPose {
	if x != nil {
		return x.Origin
	}
	return nil
}

type Vertex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pose          *MapPose               `protobuf:"bytes,2,opt,name=pose,proto3" json:"pose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vertex) Reset() {
	*x = Vertex{}
	mi := &file_proto_map_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex) ProtoMessage() {}

func (x *Vertex) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex.ProtoReflect.Descriptor instead.
func (*Vertex) Descriptor() ([]byte, []int) {
	return file_proto_map_proto_rawDescGZIP(), []int{3}
}

func (x *Vertex) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vertex) GetPose() *MapPose {
	if x != nil {
		return x.Pose
	}
	return nil
}

type MapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapMetadata   *MapMetadata           `protobuf:"bytes,1,opt,name=map_metadata,json=mapMetadata,proto3" json:"map_metadata,omitempty"`
	Vertexes      []*Vertex              `protobuf:"bytes,2,rep,name=vertexes,proto3" json:"vertexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapResponse) Reset() {
	*x = MapResponse{}
	mi := &file_proto_map_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResponse) ProtoMessage() {}

func (x *MapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResponse.ProtoReflect.Descriptor instead.
func (*MapResponse) Descriptor() ([]byte, []int) {
	return file_proto_map_proto_rawDescGZIP(), []int{4}
}

func (x *MapResponse) GetMapMetadata() *MapMetadata {
	if x != nil {
		return x.MapMetadata
	}
	return nil
}

func (x *MapResponse) GetVertexes() []*Vertex {
	if x != nil {
		return x.Vertexes
	}
	return nil
}

var File_proto_map_proto protoreflect.FileDescriptor

const file_proto_map_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/map.proto\x12\x06bridge\"\x0f\n" +
	"\rGetMapRequest\"7\n" +
	"\aMapPose\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x10\n" +
	"\x03yaw\x18\x03 \x01(\x02R\x03yaw\"\x9b\x01\n" +
	"\vMapMetadata\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\x02R\n" +
	"resolution\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12'\n" +
	"\x06origin\x18\x05 \x01(\v2\x0f.bridge.MapPoseR\x06origin\"A\n" +
	"\x06Vertex\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\x04pose\x18\x02 \x01(\v2\x0f.bridge.MapPoseR\x04pose\"q\n" +
	"\vMapResponse\x126\n" +
	"\fmap_metadata\x18\x01 \x01(\v2\x13.bridge.MapMetadataR\vmapMetadata\x12*\n" +
	"\bvertexes\x18\x02 \x03(\v2\x0e.bridge.VertexR\bvertexes2B\n" +
	"\n" +
	"MapService\x124\n" +
	"\x06GetMap\x12\x15.bridge.GetMapRequest\x1a\x13.bridge.MapResponseB<Z:github.com/nicosyncai/syncai-bridge/internal/grpcserver/pbb\x06proto3"

var (
	file_proto_map_proto_rawDescOnce sync.Once
	file_proto_map_proto_rawDescData []byte
)

func file_proto_map_proto_rawDescGZIP() []byte {
	file_proto_map_proto_rawDescOnce.Do(func() {
		file_proto_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_map_proto_rawDesc), len(file_proto_map_proto_rawDesc)))
	})
	return file_proto_map_proto_rawDescData
}

var file_proto_map_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_map_proto_goTypes = []any{
	(*GetMapRequest)(nil), // 0: bridge.GetMapRequest
	(*MapPose)(nil),       // 1: bridge.MapPose
	(*MapMetadata)(nil),   // 2: bridge.MapMetadata
	(*Vertex)(nil),        // 3: bridge.Vertex
	(*MapResponse)(nil),   // 4: bridge.MapResponse
}
var file_proto_map_proto_depIdxs = []int32{
	1, // 0: bridge.MapMetadata.origin:type_name -> bridge.MapPose
	1, // 1: bridge.Vertex.pose:type_name -> bridge.MapPose
	2, // 2: bridge.MapResponse.map_metadata:type_name -> bridge.MapMetadata
	3, // 3: bridge.MapResponse.vertexes:type_name -> bridge.Vertex
	0, // 4: bridge.MapService.GetMap:input_type -> bridge.GetMapRequest
	4, // 5: bridge.MapService.GetMap:output_type -> bridge.MapResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_map_proto_init() }
func file_proto_map_proto_init() {
	if File_proto_map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_map_proto_rawDesc), len(file_proto_map_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_map_proto_goTypes,
		DependencyIndexes: file_proto_map_proto_depIdxs,
		MessageInfos:      file_proto_map_proto_msgTypes,
	}.Build()
	File_proto_map_proto = out.File
	file_proto_map_proto_goTypes = nil
	file_proto_map_proto_depIdxs = nil
}
