// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/robot_state.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotStateService_SubscribeRobotState_FullMethodName = "/bridge.RobotStateService/SubscribeRobotState"
)

// RobotStateServiceClient is the client API for RobotStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobotStateServiceClient interface {
	SubscribeRobotState(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RobotState], error)
}

type robotStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotStateServiceClient(cc grpc.ClientConnInterface) RobotStateServiceClient {
	return &robotStateServiceClient{cc}
}

func (c *robotStateServiceClient) SubscribeRobotState(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RobotState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RobotStateService_ServiceDesc.Streams[0], RobotStateService_SubscribeRobotState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, RobotState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotStateService_SubscribeRobotStateClient = grpc.ServerStreamingClient[RobotState]

// RobotStateServiceServer is the server API for RobotStateService service.
// All implementations must embed UnimplementedRobotStateServiceServer
// for forward compatibility.
type RobotStateServiceServer interface {
	SubscribeRobotState(*SubscribeRequest, grpc.ServerStreamingServer[RobotState]) error
	mustEmbedUnimplementedRobotStateServiceServer()
}

// UnimplementedRobotStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotStateServiceServer struct{}

func (UnimplementedRobotStateServiceServer) SubscribeRobotState(*SubscribeRequest, grpc.ServerStreamingServer[RobotState]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRobotState not implemented")
}
func (UnimplementedRobotStateServiceServer) mustEmbedUnimplementedRobotStateServiceServer() {}
func (UnimplementedRobotStateServiceServer) testEmbeddedByValue()                           {}

// UnsafeRobotStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotStateServiceServer will
// result in compilation errors.
type UnsafeRobotStateServiceServer interface {
	mustEmbedUnimplementedRobotStateServiceServer()
}

func RegisterRobotStateServiceServer(s grpc.ServiceRegistrar, srv RobotStateServiceServer) {
	// If the following call panics, it indicates UnimplementedRobotStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotStateService_ServiceDesc, srv)
}

func _RobotStateService_SubscribeRobotState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RobotStateServiceServer).SubscribeRobotState(m, &grpc.GenericServerStream[SubscribeRequest, RobotState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotStateService_SubscribeRobotStateServer = grpc.ServerStreamingServer[RobotState]

// RobotStateService_ServiceDesc is the grpc.ServiceDesc for RobotStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.RobotStateService",
	HandlerType: (*RobotStateServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRobotState",
			Handler:       _RobotStateService_SubscribeRobotState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/robot_state.proto",
}
