// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/robot_state.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_robot_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_state_proto_rawDescGZIP(), []int{0}
}

type Pose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Yaw           float32                `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pose) Reset() {
	*x = Pose{}
	mi := &file_proto_robot_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pose) ProtoMessage() {}

func (x *Pose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pose.ProtoReflect.Descriptor instead.
func (*Pose) Descriptor() ([]byte, []int) {
	return file_proto_robot_state_proto_rawDescGZIP(), []int{1}
}

func (x *Pose) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pose) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Pose) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type Twist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vx            float32                `protobuf:"fixed32,1,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy            float32                `protobuf:"fixed32,2,opt,name=vy,proto3" json:"vy,omitempty"`
	Omega         float32                `protobuf:"fixed32,3,opt,name=omega,proto3" json:"omega,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Twist) Reset() {
	*x = Twist{}
	mi := &file_proto_robot_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Twist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Twist) ProtoMessage() {}

func (x *Twist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Twist.ProtoReflect.Descriptor instead.
func (*Twist) Descriptor() ([]byte, []int) {
	return file_proto_robot_state_proto_rawDescGZIP(), []int{2}
}

func (x *Twist) GetVx() float32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *Twist) GetVy() float32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *Twist) GetOmega() float32 {
	if x != nil {
		return x.Omega
	}
	return 0
}

type Battery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    float32                `protobuf:"fixed32,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Voltage       float32                `protobuf:"fixed32,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Battery) Reset() {
	*x = Battery{}
	mi := &file_proto_robot_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Battery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Battery) ProtoMessage() {}

func (x *Battery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Battery.ProtoReflect.Descriptor instead.
func (*Battery) Descriptor() ([]byte, []int) {
	return file_proto_robot_state_proto_rawDescGZIP(), []int{3}
}

func (x *Battery) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Battery) GetVoltage() float32 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

type RobotState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	RobotName     string                 `protobuf:"bytes,2,opt,name=robot_name,json=robotName,proto3" json:"robot_name,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Map           string                 `protobuf:"bytes,4,opt,name=map,proto3" json:"map,omitempty"`
	Pose          *Pose                  `protobuf:"bytes,5,opt,name=pose,proto3" json:"pose,omitempty"`
	Twist         *Twist                 `protobuf:"bytes,6,opt,name=twist,proto3" json:"twist,omitempty"`
	Battery       *Battery               `protobuf:"bytes,7,opt,name=battery,proto3" json:"battery,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotState) Reset() {
	*x = RobotState{}
	mi := &file_proto_robot_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotState) ProtoMessage() {}

func (x *RobotState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotState.ProtoReflect.Descriptor instead.
func (*RobotState) Descriptor() ([]byte, []int) {
	return file_proto_robot_state_proto_rawDescGZIP(), []int{4}
}

func (x *RobotState) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RobotState) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

func (x *RobotState) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RobotState) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *RobotState) GetPose() *Pose {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *RobotState) GetTwist() *Twist {
	if x != nil {
		return x.Twist
	}
	return nil
}

func (x *RobotState) GetBattery() *Battery {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *RobotState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_robot_state_proto protoreflect.FileDescriptor

const file_proto_robot_state_proto_rawDesc = "" +
	"\n" +
	"\x17proto/robot_state.proto\x12\x06bridge\"\x12\n" +
	"\x10SubscribeRequest\"4\n" +
	"\x04Pose\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x10\n" +
	"\x03yaw\x18\x03 \x01(\x02R\x03yaw\"=\n" +
	"\x05Twist\x12\x0e\n" +
	"\x02vx\x18\x01 \x01(\x02R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x02 \x01(\x02R\x02vy\x12\x14\n" +
	"\x05omega\x18\x03 \x01(\x02R\x05omega\"C\n" +
	"\aBattery\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x02R\n" +
	"percentage\x12\x18\n" +
	"\avoltage\x18\x02 \x01(\x02R\avoltage\"\xfe\x01\n" +
	"\n" +
	"RobotState\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x1d\n" +
	"\n" +
	"robot_name\x18\x02 \x01(\tR\trobotName\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x10\n" +
	"\x03map\x18\x04 \x01(\tR\x03map\x12 \n" +
	"\x04pose\x18\x05 \x01(\v2\f.bridge.PoseR\x04pose\x12#\n" +
	"\x05twist\x18\x06 \x01(\v2\r.bridge.TwistR\x05twist\x12)\n" +
	"\abattery\x18\a \x01(\v2\x0f.bridge.BatteryR\abattery\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp2Z\n" +
	"\x11RobotStateService\x12E\n" +
	"\x13SubscribeRobotState\x12\x18.bridge.SubscribeRequest\x1a\x12.bridge.RobotState0\x01B<Z:github.com/nicosyncai/syncai-bridge/internal/grpcserver/pbb\x06proto3"

var (
	file_proto_robot_state_proto_rawDescOnce sync.Once
	file_proto_robot_state_proto_rawDescData []byte
)

func file_proto_robot_state_proto_rawDescGZIP() []byte {
	file_proto_robot_state_proto_rawDescOnce.Do(func() {
		file_proto_robot_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_robot_state_proto_rawDesc), len(file_proto_robot_state_proto_rawDesc)))
	})
	return file_proto_robot_state_proto_rawDescData
}

var file_proto_robot_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_robot_state_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: bridge.SubscribeRequest
	(*Pose)(nil),             // 1: bridge.Pose
	(*Twist)(nil),            // 2: bridge.Twist
	(*Battery)(nil),          // 3: bridge.Battery
	(*RobotState)(nil),       // 4: bridge.RobotState
}
var file_proto_robot_state_proto_depIdxs = []int32{
	1, // 0: bridge.RobotState.pose:type_name -> bridge.Pose
	2, // 1: bridge.RobotState.twist:type_name -> bridge.Twist
	3, // 2: bridge.RobotState.battery:type_name -> bridge.Battery
	0, // 3: bridge.RobotStateService.SubscribeRobotState:input_type -> bridge.SubscribeRequest
	4, // 4: bridge.RobotStateService.SubscribeRobotState:output_type -> bridge.RobotState
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_robot_state_proto_init() }
func file_proto_robot_state_proto_init() {
	if File_proto_robot_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_robot_state_proto_rawDesc), len(file_proto_robot_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_robot_state_proto_goTypes,
		DependencyIndexes: file_proto_robot_state_proto_depIdxs,
		MessageInfos:      file_proto_robot_state_proto_msgTypes,
	}.Build()
	File_proto_robot_state_proto = out.File
	file_proto_robot_state_proto_goTypes = nil
	file_proto_robot_state_proto_depIdxs = nil
}
