// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/task.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskAction int32

const (
	TaskAction_TASK_ACTION_UNSPECIFIED TaskAction = 0
	TaskAction_TASK                    TaskAction = 1
	TaskAction_COMMAND                 TaskAction = 2
)

// Enum value maps for TaskAction.
var (
	TaskAction_name = map[int32]string{
		0: "TASK_ACTION_UNSPECIFIED",
		1: "TASK",
		2: "COMMAND",
	}
	TaskAction_value = map[string]int32{
		"TASK_ACTION_UNSPECIFIED": 0,
		"TASK":                    1,
		"COMMAND":                 2,
	}
)

func (x TaskAction) Enum() *TaskAction {
	p := new(TaskAction)
	*p = x
	return p
}

func (x TaskAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[0].Descriptor()
}

func (TaskAction) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[0]
}

func (x TaskAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskAction.Descriptor instead.
func (TaskAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

type StepType int32

const (
	StepType_STEP_TYPE_UNSPECIFIED StepType = 0
	StepType_MOVE                  StepType = 1
	StepType_WAIT                  StepType = 2
	StepType_DOOR                  StepType = 3
	StepType_CHARGE                StepType = 4
	StepType_NAVIGATE_WITH_ALERT   StepType = 5
)

// Enum value maps for StepType.
var (
	StepType_name = map[int32]string{
		0: "STEP_TYPE_UNSPECIFIED",
		1: "MOVE",
		2: "WAIT",
		3: "DOOR",
		4: "CHARGE",
		5: "NAVIGATE_WITH_ALERT",
	}
	StepType_value = map[string]int32{
		"STEP_TYPE_UNSPECIFIED": 0,
		"MOVE":                  1,
		"WAIT":                  2,
		"DOOR":                  3,
		"CHARGE":                4,
		"NAVIGATE_WITH_ALERT":   5,
	}
)

func (x StepType) Enum() *StepType {
	p := new(StepType)
	*p = x
	return p
}

func (x StepType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[1].Descriptor()
}

func (StepType) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[1]
}

func (x StepType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepType.Descriptor instead.
func (StepType) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_PENDING                 TaskStatus = 1
	TaskStatus_IN_PROGRESS             TaskStatus = 2
	TaskStatus_COMPLETED               TaskStatus = 3
	TaskStatus_FAILED                  TaskStatus = 4
	TaskStatus_CANCELLED               TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "IN_PROGRESS",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"PENDING":                 1,
		"IN_PROGRESS":             2,
		"COMPLETED":               3,
		"FAILED":                  4,
		"CANCELLED":               5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[2].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[2]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{2}
}

type PoseParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	R             float32                `protobuf:"fixed32,3,opt,name=r,proto3" json:"r,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoseParams) Reset() {
	*x = PoseParams{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoseParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoseParams) ProtoMessage() {}

func (x *PoseParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoseParams.ProtoReflect.Descriptor instead.
func (*PoseParams) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *PoseParams) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PoseParams) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PoseParams) GetR() float32 {
	if x != nil {
		return x.R
	}
	return 0
}

type WaitParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationSec   float32                `protobuf:"fixed32,1,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitParams) Reset() {
	*x = WaitParams{}
	mi := &file_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitParams) ProtoMessage() {}

func (x *WaitParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitParams.ProtoReflect.Descriptor instead.
func (*WaitParams) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *WaitParams) GetDurationSec() float32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type DoorParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          bool                   `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoorParams) Reset() {
	*x = DoorParams{}
	mi := &file_proto_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoorParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoorParams) ProtoMessage() {}

func (x *DoorParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoorParams.ProtoReflect.Descriptor instead.
func (*DoorParams) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{2}
}

func (x *DoorParams) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

type Step struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type  StepType               `protobuf:"varint,3,opt,name=type,proto3,enum=bridge.StepType" json:"type,omitempty"`
	// Types that are valid to be assigned to Params:
	//
	//	*Step_PoseParams
	//	*Step_WaitParams
	//	*Step_DoorParams
	Params        isStep_Params `protobuf_oneof:"params"`
	Status        TaskStatus    `protobuf:"varint,7,opt,name=status,proto3,enum=bridge.TaskStatus" json:"status,omitempty"`
	ErrorMsg      string        `protobuf:"bytes,8,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_proto_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{3}
}

func (x *Step) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetType() StepType {
	if x != nil {
		return x.Type
	}
	return StepType_STEP_TYPE_UNSPECIFIED
}

func (x *Step) GetParams() isStep_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Step) GetPoseParams() *PoseParams {
	if x != nil {
		if x, ok := x.Params.(*Step_PoseParams); ok {
			return x.PoseParams
		}
	}
	return nil
}

func (x *Step) GetWaitParams() *WaitParams {
	if x != nil {
		if x, ok := x.Params.(*Step_WaitParams); ok {
			return x.WaitParams
		}
	}
	return nil
}

func (x *Step) GetDoorParams() *DoorParams {
	if x != nil {
		if x, ok := x.Params.(*Step_DoorParams); ok {
			return x.DoorParams
		}
	}
	return nil
}

func (x *Step) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Step) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type isStep_Params interface {
	isStep_Params()
}

type Step_PoseParams struct {
	PoseParams *PoseParams `protobuf:"bytes,4,opt,name=pose_params,json=poseParams,proto3,oneof"`
}

type Step_WaitParams struct {
	WaitParams *WaitParams `protobuf:"bytes,5,opt,name=wait_params,json=waitParams,proto3,oneof"`
}

type Step_DoorParams struct {
	DoorParams *DoorParams `protobuf:"bytes,6,opt,name=door_params,json=doorParams,proto3,oneof"`
}

func (*Step_PoseParams) isStep_Params() {}

func (*Step_WaitParams) isStep_Params() {}

func (*Step_DoorParams) isStep_Params() {}

type TaskPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*Step                `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskPayload) Reset() {
	*x = TaskPayload{}
	mi := &file_proto_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskPayload) ProtoMessage() {}

func (x *TaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskPayload.ProtoReflect.Descriptor instead.
func (*TaskPayload) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskPayload) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Task struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Action           TaskAction             `protobuf:"varint,1,opt,name=action,proto3,enum=bridge.TaskAction" json:"action,omitempty"`
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp        float64                `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload          *TaskPayload           `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status           TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=bridge.TaskStatus" json:"status,omitempty"`
	CurrentStepIndex int32                  `protobuf:"varint,6,opt,name=current_step_index,json=currentStepIndex,proto3" json:"current_step_index,omitempty"`
	ErrorMsg         string                 `protobuf:"bytes,7,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	WorkflowId       string                 `protobuf:"bytes,8,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	CompletedAt      float64                `protobuf:"fixed64,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetAction() TaskAction {
	if x != nil {
		return x.Action
	}
	return TaskAction_TASK_ACTION_UNSPECIFIED
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Task) GetPayload() *TaskPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetCurrentStepIndex() int32 {
	if x != nil {
		return x.CurrentStepIndex
	}
	return 0
}

func (x *Task) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *Task) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Task) GetCompletedAt() float64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{6}
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        TaskAction             `protobuf:"varint,1,opt,name=action,proto3,enum=bridge.TaskAction" json:"action,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       *TaskPayload           `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTaskRequest) GetAction() TaskAction {
	if x != nil {
		return x.Action
	}
	return TaskAction_TASK_ACTION_UNSPECIFIED
}

func (x *CreateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTaskRequest) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CreateTaskRequest) GetPayload() *TaskPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=bridge.TaskStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *CreateTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x12\x06bridge\"6\n" +
	"\n" +
	"PoseParams\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01r\x18\x03 \x01(\x02R\x01r\"/\n" +
	"\n" +
	"WaitParams\x12!\n" +
	"\fduration_sec\x18\x01 \x01(\x02R\vdurationSec\" \n" +
	"\n" +
	"DoorParams\x12\x12\n" +
	"\x04open\x18\x01 \x01(\bR\x04open\"\xc8\x02\n" +
	"\x04Step\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.bridge.StepTypeR\x04type\x125\n" +
	"\vpose_params\x18\x04 \x01(\v2\x12.bridge.PoseParamsH\x00R\n" +
	"poseParams\x125\n" +
	"\vwait_params\x18\x05 \x01(\v2\x12.bridge.WaitParamsH\x00R\n" +
	"waitParams\x125\n" +
	"\vdoor_params\x18\x06 \x01(\v2\x12.bridge.DoorParamsH\x00R\n" +
	"doorParams\x12*\n" +
	"\x06status\x18\a \x01(\x0e2\x12.bridge.TaskStatusR\x06status\x12\x1b\n" +
	"\terror_msg\x18\b \x01(\tR\berrorMsgB\b\n" +
	"\x06params\"1\n" +
	"\vTaskPayload\x12\"\n" +
	"\x05steps\x18\x01 \x03(\v2\f.bridge.StepR\x05steps\"\xca\x02\n" +
	"\x04Task\x12*\n" +
	"\x06action\x18\x01 \x01(\x0e2\x12.bridge.TaskActionR\x06action\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x01R\ttimestamp\x12-\n" +
	"\apayload\x18\x04 \x01(\v2\x13.bridge.TaskPayloadR\apayload\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.bridge.TaskStatusR\x06status\x12,\n" +
	"\x12current_step_index\x18\x06 \x01(\x05R\x10currentStepIndex\x12\x1b\n" +
	"\terror_msg\x18\a \x01(\tR\berrorMsg\x12\x1f\n" +
	"\vworkflow_id\x18\b \x01(\tR\n" +
	"workflowId\x12!\n" +
	"\fcompleted_at\x18\t \x01(\x01R\vcompletedAt\"\x12\n" +
	"\x10ListTasksRequest\"7\n" +
	"\x11ListTasksResponse\x12\"\n" +
	"\x05tasks\x18\x01 \x03(\v2\f.bridge.TaskR\x05tasks\"\x9c\x01\n" +
	"\x11CreateTaskRequest\x12*\n" +
	"\x06action\x18\x01 \x01(\x0e2\x12.bridge.TaskActionR\x06action\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x01R\ttimestamp\x12-\n" +
	"\apayload\x18\x04 \x01(\v2\x13.bridge.TaskPayloadR\apayload\"j\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.bridge.TaskStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId*@\n" +
	"\n" +
	"TaskAction\x12\x1b\n" +
	"\x17TASK_ACTION_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TASK\x10\x01\x12\v\n" +
	"\aCOMMAND\x10\x02*h\n" +
	"\bStepType\x12\x19\n" +
	"\x15STEP_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04MOVE\x10\x01\x12\b\n" +
	"\x04WAIT\x10\x02\x12\b\n" +
	"\x04DOOR\x10\x03\x12\n" +
	"\n" +
	"\x06CHARGE\x10\x04\x12\x17\n" +
	"\x13NAVIGATE_WITH_ALERT\x10\x05*q\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x052\xc5\x01\n" +
	"\vTaskService\x12C\n" +
	"\n" +
	"CreateTask\x12\x19.bridge.CreateTaskRequest\x1a\x1a.bridge.CreateTaskResponse\x12@\n" +
	"\tListTasks\x12\x18.bridge.ListTasksRequest\x1a\x19.bridge.ListTasksResponse\x12/\n" +
	"\aGetTask\x12\x16.bridge.GetTaskRequest\x1a\f.bridge.TaskB<Z:github.com/nicosyncai/syncai-bridge/internal/grpcserver/pbb\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_task_proto_goTypes = []any{
	(TaskAction)(0),            // 0: bridge.TaskAction
	(StepType)(0),              // 1: bridge.StepType
	(TaskStatus)(0),            // 2: bridge.TaskStatus
	(*PoseParams)(nil),         // 3: bridge.PoseParams
	(*WaitParams)(nil),         // 4: bridge.WaitParams
	(*DoorParams)(nil),         // 5: bridge.DoorParams
	(*Step)(nil),               // 6: bridge.Step
	(*TaskPayload)(nil),        // 7: bridge.TaskPayload
	(*Task)(nil),               // 8: bridge.Task
	(*ListTasksRequest)(nil),   // 9: bridge.ListTasksRequest
	(*ListTasksResponse)(nil),  // 10: bridge.ListTasksResponse
	(*CreateTaskRequest)(nil),  // 11: bridge.CreateTaskRequest
	(*CreateTaskResponse)(nil), // 12: bridge.CreateTaskResponse
	(*GetTaskRequest)(nil),     // 13: bridge.GetTaskRequest
}
var file_proto_task_proto_depIdxs = []int32{
	1,  // 0: bridge.Step.type:type_name -> bridge.StepType
	3,  // 1: bridge.Step.pose_params:type_name -> bridge.PoseParams
	4,  // 2: bridge.Step.wait_params:type_name -> bridge.WaitParams
	5,  // 3: bridge.Step.door_params:type_name -> bridge.DoorParams
	2,  // 4: bridge.Step.status:type_name -> bridge.TaskStatus
	6,  // 5: bridge.TaskPayload.steps:type_name -> bridge.Step
	0,  // 6: bridge.Task.action:type_name -> bridge.TaskAction
	7,  // 7: bridge.Task.payload:type_name -> bridge.TaskPayload
	2,  // 8: bridge.Task.status:type_name -> bridge.TaskStatus
	8,  // 9: bridge.ListTasksResponse.tasks:type_name -> bridge.Task
	0,  // 10: bridge.CreateTaskRequest.action:type_name -> bridge.TaskAction
	7,  // 11: bridge.CreateTaskRequest.payload:type_name -> bridge.TaskPayload
	2,  // 12: bridge.CreateTaskResponse.status:type_name -> bridge.TaskStatus
	11, // 13: bridge.TaskService.CreateTask:input_type -> bridge.CreateTaskRequest
	9,  // 14: bridge.TaskService.ListTasks:input_type -> bridge.ListTasksRequest
	13, // 15: bridge.TaskService.GetTask:input_type -> bridge.GetTaskRequest
	12, // 16: bridge.TaskService.CreateTask:output_type -> bridge.CreateTaskResponse
	10, // 17: bridge.TaskService.ListTasks:output_type -> bridge.ListTasksResponse
	8,  // 18: bridge.TaskService.GetTask:output_type -> bridge.Task
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	file_proto_task_proto_msgTypes[3].OneofWrappers = []any{
		(*Step_PoseParams)(nil),
		(*Step_WaitParams)(nil),
		(*Step_DoorParams)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		EnumInfos:         file_proto_task_proto_enumTypes,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
